version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./local.Dockerfile
    tty: true
    command: npm run test:e2e-headless
    environment:
      DISPLAY: xserver:0 
      UV_THREADPOOL_SIZE: 2
  api:
    build: ./api
    command: npm start
    depends_on:
      - mongodb
    environment:
      - E2E=1
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.7
  xserver:
    image: codeanker/xserver:latest
    ports:
      - 5900:5900
    environment:
      VNC_PASSWORD: yourPW
      XFB_SCREEN: 1920x1080x24
      XFB_SCREEN_DPI: 100